config/routes.rb
ChatworkFake::Application.routes.draw do
  root "static_pages#home"
  devise_for :users
  devise_scope :user do
    get "sign_up", to: "devise/registrations#new"
    get "sign_in", to: "devise/sessions#new"
  end
  resources :users do
    resources :messages
  end

  

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  default_scope -> {order("created_at DESC")}
  validates :content, presence: true, length: {maximum: 1000}
  validates :user_id, presence: true
  scope :chat_with_friend, ->user_id,friend_id{where"((user_id = :user_id and friend_id = :friend_id) OR (user_id = :friend_id and friend_id = :user_id))",user_id: user_id, friend_id: friend_id}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def show
    @receiver = User.find(params[:id])
    @histories = @receiver.histories_with(current_user).paginate(:page => params[:page], :order => 'created_at')
    respond_to do |format|
      format.html { render :partial => "shared/histories", :histories => @histories, :receiver => @receiver }
      format.js {
        render 'histories/show'
      }
    end
  end

  def create
    @message = current_user.messages.new(message_params)
    if @message.save
      # respond_to do |format|
      #   format.html { render :partial => "histories/message", :message => @message }
      #   format.js {
      #     render 'histories/create'
      #   }
      # end
      #user_msg :new_message, message[:msg_body].dup
      logger.info "----------start----------"
      logger.info @message.content
      event = WebsocketRails::Event.new(:new_message, data: {
        user_name:  @message.user_id, 
        received:   Time.now.to_s(:short), 
        msg_body:   ERB::Util.html_escape(@message.content) 
      })
      #WebsocketRails["system"].trigger event
      #binding.pry
      # WebsocketRails.users[@message.receiver.id.to_s].send_message :new_message, { 
      #WebsocketRails.users[@message.receiver.id.to_s].trigger event
      WebsocketRails.users.each do |connection|
        event = WebsocketRails::Event.new(:new_message, data: {
          user_name:  @message.user_id, 
          received:   Time.now.to_s(:short), 
          msg_body:   ERB::Util.html_escape(@message.content) 
        })
        connection.trigger event
      end
      # WebsocketRails.broadcast_message Event.new(:new_message, data: {
      #   user_name:  @message.poster.name, 
      #   received:   Time.now.to_s(:short), 
      #   msg_body:   ERB::Util.html_escape(@message.content) 
      # })
      # WebsocketRails.users.send_message :new_message, { 
      # user_name:  @message.poster.name, 
      # received:   Time.now.to_s(:short), 
      # msg_body:   ERB::Util.html_escape(@message.content) 
      # }
      #WebsocketRails[@message.receiver.email].trigger :new_message, @message.content
      logger.info "----------end----------"
    end
  end

  def destroy
  end

  private

    def message_params
      params.require(:message).permit(:content, :friend_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def edit
  end

  def update
    if user_params
      current_user.update_attributes user_params
    end
    redirect_to :back
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
    @messages = Message.chat_with_friend current_user.id, @user.id
  end

  private
  def user_params
    params.require(:user).permit :name, :birthday, :gender, :company
  end

  def correct_user
    @user = User.find params[:id]
    redirect_to user_path(current_user) unless current_user==@user
  end 
end

app/controllers/web_socket_controller.rb
class WebSocketController < WebsocketRails::BaseController
  $connection_store = {}

  def client_connected
    logger.info "------------client_connected----------"
    logger.info "#{client_id}"
    system_msg :new_message, "client #{client_id} connected"
  end

  def new_message
    user_msg :new_message, message[:msg_body].dup
  end

  def new_user
    logger.info "------------------new_user--------------"
    #logger.info "user_id: " + message[:user_id].to_s + "----"
    #connection_store[:user] = { user_name: message[:user_id] }
    user_msg :new_message, "add new user"
    broadcast_user_list
  end

  def change_username
    connection_store[:user] = sanitize(message)
    broadcast_user_list
  end

  def delete_user
    connection_store[:user] = nil
    system_msg "client #{client_id} disconnected"
    broadcast_user_list
  end

  def broadcast_user_list
    users = connection_store.collect_all(:user)
    broadcast_message :user_list, users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Edit profile", edit_user_path(current_user) %></li>
            <li><%= link_to "Edit password", edit_user_registration_path(current_user) %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign in", sign_in_path %></li>
            <li><%= link_to "Sign up", sign_up_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "Chatwork" %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/create.js.erb
 $('.posts').append("<%= escape_javascript(render(:partial => "shared/message", 
  :locals => {message: @message})) %>");
 $('#__content').val('');

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_message.html.erb
<div>
  <li class="message " id="__message_<%= message.id %>">

    <input type="hidden" id="_message_id" value="<%= message.id %>">
    <span id="_message_content"><%= message.user.email %> <%= message.content %></span>
    <span class="show" id="_hidden">
      <%= link_to "Trich dan", "#" , class: "quote " %>
    </span>
  </li>
</div>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
  <div class ="left-sidebar">
    <ul>
      <% @users.each do |user| %>
        <li>
          <%= link_to user.email, user_path(user) %>
        </li>
      <% end %>
    </ul>
  </div>
<%= link_to "Test", "#", class: "btn" %>

<script>
$(function() {
  $(".btn").click(function (){
    $( ".dialog" ).dialog( {
            show : "slide",
            hide : "toggle",
            width: 800,
            height: 500,
            modal: true,
            title: "Edit profile"
        });
  });
});
</script>

<div class="dialog" style="display: none">
  <h3>Change Users Profile</h3>
  <%= form_for current_user do |f| %>
    <%= f.label :name %>
    <div class="input_new"><%= f.text_field :name %></div>
    <%= f.label :birthday %>
    <div class="date_select">
      <%= f.date_select :birthday, order: [:day, :month, :year],  start_year: Time.now.year - 100, end_year: Time.now.year %>
    </div>
    <%= f.radio_button :gender, "male" %> Male
    <%= f.radio_button :gender, "female" %> Female<br>

    <%= f.label :company %>
    <%= f.text_field :company %>
    <%= f.label :address %>
    <%= f.text_area :address %>

    <div><%= f.submit "Update" %></div>
  <% end %>
  <%= link_to "Cancel", :back %>
</div>
<% else %>
  <h1>Wellcome to chatwork</h1>
<% end %>

app/views/users/edit.html.erb
<div z="edit_profile">
  <h3>Change Users Profile</h3>
  <%= form_for current_user do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name %>
    <div class="input_new"><%= f.text_field :name %></div>
    <%= f.label :birthday %>
    <div class="date_select">
      <%= f.date_select :birthday, order: [:day, :month, :year],  start_year: Time.now.year - 100, end_year: Time.now.year %>
    </div>
    <%= f.radio_button :gender, "male" %> Male
    <%= f.radio_button :gender, "female" %> Female<br>

    <%= f.label :company %>
    <%= f.text_field :company %>
    <%= f.label :address %>
    <%= f.text_area :address %>

    <div><%= f.submit "Update" %></div>
  <% end %>
  <%= link_to "Cancel", :back %>
</div>

app/views/users/show.html.erb
<div class ="left-sidebar">
  <h2><%= current_user.email %></h2>
  <ol>
    <% @users.each do |user| %>
      <li>
        <%= link_to user.email, user_path(user) %>
      </li>
    <% end %>
  </ol>
</div>
<div class="main-content">
  <%= form_for [@user, Message.new], remote: true do |message| %>
    <div class="field">
      <%= render "shared/error_messages", object: message.object %>
      <%= message.hidden_field :friend_id, value: @user.id %>
      <%= message.text_area :content, id: "__content" %> 
      <%= message.submit "Send", class: "btn btn-primary ", id: "send" %>
    </div>
  <% end %>
</div>
<div>
  Message:
  <ul class="posts">
    <% @messages.each do |message| %>
    <%= render "shared/message", message: message %>
    <% end %>
  </ul>
</div>
<script>
  $(".message").each(function() {
    var _message_id = $(this).find('#_message_id').val();
    var message = $(this).find('#_message_content').html();
    $(this).mouseover(function(){
      $(this).find(".quote").show();
    });
    $(this).mouseout(function(){
      $(this).find(".quote").hide();
    });
    $(this).find(".quote").click(function(event){
      event.preventDefault();
      $('#message_content').val("[id=" + _message_id + "] " + message + "\n");
    });
  });
</script>